resources:
- name: test-api
  type: git
  source: 
    uri: https://github.com/BenjaminNath/tourOfHeroes
    branch: master
- name: bazaz-demo-cf
  type: cf
  source:
    api: https://api.sys.gn01.pcf.dcsg.com
    username: ((cf_user_nonprod))
    password: ((cf_password_nonprod))
    organization: bazaz-demo
    space: dev
    skip_cert_check: true

jobs:
- name: build-and-deploy
  plan: 
  - get: test-api
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
      - name: test-api
      outputs:
      - name: compiledHeroes
      run:
        path: ./test-api/shellScripts/testing_shell.sh
  - put: bazaz-demo-cf
    params:
      manifest: test-api/manifest.yml
      path: test-api/dist/